---
version: "3.7"
services:
    # ---------------------------------------------------------------------
    # | Nginx-Service                                                     |
    # ---------------------------------------------------------------------
    nginx-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginx-container
        restart: unless-stopped
        labels:
            - traefik.enable=true
            # Routers
            - traefik.http.routers.poc--mod-prj-str.entrypoints=web
            - traefik.http.routers.poc--mod-prj-str.middlewares=test-redirectscheme
            - traefik.http.routers.poc--mod-prj-str-secure.entrypoints=websecure
            - traefik.http.routers.poc--mod-prj-str-secure.tls.certresolver=myresolver
            - traefik.http.routers.poc--mod-prj-str-secure.tls=true
            - traefik.http.routers.poc--mod-prj-str-secure.middlewares=test-compress,test-redirectscheme
            # Services
            - traefik.http.services.poc--mod-prj-str-secure.loadbalancer.server.port=80
            # Middlewares
            - traefik.http.middlewares.test-compress.compress=true
            - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
            - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
            - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443